"""Dynamic order-level sequencing helpers.

The production process inside one product is still generated by
``TaskGenerator`` and the dynamic dispatch is still computed by
``DiscreteEventExperiment.run_proposed``.  This module only converts the task
timeline back into an order-level view that is easier to show in a small input
window.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Literal, Tuple

from interfaces.types import Order, Task
from scheduler.experiment import DiscreteEventExperiment, ExperimentResult, ScheduleRecord


QualityMode = Literal["AUTO", "OK", "NG"]


@dataclass(frozen=True)
class DynamicOrderInput:
    order_id: str
    product_type: str
    quantity: int = 1
    priority: int = 1
    due_time: float = 0.0
    arrival_time: float = 0.0
    quality: QualityMode = "AUTO"


@dataclass(frozen=True)
class OrderSequenceRow:
    rank: int
    order_id: str
    product_type: str
    priority: int
    arrival_time: float
    due_time: float
    quality_result: str
    first_start: float
    inspect_end: float
    completion_time: float
    branch: str
    process_chain: str


class QualityOverrideExperiment(DiscreteEventExperiment):
    """Discrete-event experiment with optional user-provided quality results."""

    def __init__(
        self,
        quality_overrides: Dict[str, str] | None = None,
        scoring_weights: Dict[str, float] | None = None,
    ):
        super().__init__()
        self.quality_overrides = quality_overrides or {}
        if scoring_weights:
            self.scoring_config = {**self.scoring_config, **scoring_weights}

    def _quality_for(self, task: Task) -> str:
        explicit = self.quality_overrides.get(task.order_id)
        if explicit in ("OK", "NG"):
            return explicit
        return super()._quality_for(task)


def expand_quality_overrides(order_inputs: Iterable[DynamicOrderInput]) -> Dict[str, str]:
    overrides: Dict[str, str] = {}
    for item in order_inputs:
        if item.quality not in ("OK", "NG"):
            continue
        for unit_index in range(max(int(item.quantity), 1)):
            suffix = "" if int(item.quantity) == 1 else f"-{unit_index + 1:02d}"
            overrides[f"{item.order_id}{suffix}"] = item.quality
    return overrides


def to_orders(order_inputs: Iterable[DynamicOrderInput]) -> List[Order]:
    orders: List[Order] = []
    for item in order_inputs:
        orders.append(
            Order(
                order_id=item.order_id,
                product_type=item.product_type,
                priority=int(item.priority),
                quantity=max(int(item.quantity), 1),
                due_time=float(item.due_time),
                arrival_time=float(item.arrival_time),
            )
        )
    return orders


def plan_dynamic_order_sequence(
    order_inputs: Iterable[DynamicOrderInput],
    scoring_weights: Dict[str, float] | None = None,
    defects_per_100: float | None = None,
) -> Tuple[ExperimentResult, List[OrderSequenceRow]]:
    """Run the existing proposed scheduler and return an order-level sequence.

    The returned row order is the recommended order-start sequence.  Detailed
    task interleaving remains available in ``result.records``.
    """

    inputs = expand_order_inputs_as_units(order_inputs)
    experiment = QualityOverrideExperiment(
        expand_quality_overrides_with_policy(inputs, defects_per_100),
        scoring_weights,
    )
    result = experiment.run_proposed(to_orders(inputs))
    rows = summarize_order_sequence(result.records, _expanded_order_attributes(inputs))
    return result, rows


def expand_quality_overrides_with_policy(
    order_inputs: Iterable[DynamicOrderInput],
    defects_per_100: float | None = None,
) -> Dict[str, str]:
    """Build deterministic quality overrides for explicit and AUTO orders.

    Explicit OK/NG inputs always win.  When ``defects_per_100`` is provided,
    AUTO orders are also assigned deterministic OK/NG labels so that GUI,
    preview, CoppeliaSim animation, and final evaluation use the same quality
    result.  For example, 100 AUTO units with ``defects_per_100=2`` generate
    exactly two NG units spread across the sequence.
    """

    expanded = expand_order_inputs_as_units(order_inputs)
    overrides = expand_quality_overrides(expanded)
    if defects_per_100 is None:
        return overrides

    total_units = len(expanded)
    auto_order_ids = [item.order_id for item in expanded if item.quality == "AUTO"]
    if not auto_order_ids:
        return overrides

    explicit_ng = sum(1 for item in expanded if item.quality == "NG")
    target_ng = round(max(float(defects_per_100), 0.0) * total_units / 100.0)
    auto_ng = max(0, min(len(auto_order_ids), int(target_ng) - explicit_ng))

    ng_positions: set[int] = set()
    if auto_ng > 0:
        span = len(auto_order_ids)
        for index in range(auto_ng):
            position = round((index + 1) * (span + 1) / (auto_ng + 1)) - 1
            ng_positions.add(max(0, min(span - 1, position)))

    for index, order_id in enumerate(auto_order_ids):
        overrides[order_id] = "NG" if index in ng_positions else "OK"
    return overrides


def quality_evaluation(
    result: ExperimentResult,
    defects_per_100: float | None = None,
) -> Dict[str, float]:
    """Summarize quality and timing metrics for the demo window/report."""

    completed_order_ids = {
        record.order_id
        for record in result.records
        if record.process in ("sort_good", "sort_defect")
    }
    good_count = sum(
        1
        for record in result.records
        if record.process == "sort_good" and record.order_id in completed_order_ids
    )
    defect_count = sum(
        1
        for record in result.records
        if record.process == "sort_defect" and record.order_id in completed_order_ids
    )
    total = good_count + defect_count
    success_rate = (good_count / total * 100.0) if total else 0.0
    configured_defect_rate = max(float(defects_per_100 or 0.0), 0.0)
    return {
        "total_products": float(total),
        "good_count": float(good_count),
        "defect_count": float(defect_count),
        "success_rate": success_rate,
        "configured_defects_per_100": configured_defect_rate,
        "configured_good_rate": max(0.0, 100.0 - configured_defect_rate),
        "makespan": float(result.makespan),
        "conflict_count": float(result.conflict_count),
        "weighted_tardiness": float(result.weighted_tardiness),
        "post_inspection_avg_clearance_wait": float(result.post_inspection_avg_clearance_wait),
    }


def expand_order_inputs_as_units(order_inputs: Iterable[DynamicOrderInput]) -> List[DynamicOrderInput]:
    """Split quantity batches into independent unit orders for resequencing."""
    expanded: List[DynamicOrderInput] = []
    for item in order_inputs:
        quantity = max(int(item.quantity), 1)
        if quantity == 1:
            expanded.append(
                DynamicOrderInput(
                    order_id=item.order_id,
                    product_type=item.product_type,
                    quantity=1,
                    priority=item.priority,
                    due_time=item.due_time,
                    arrival_time=item.arrival_time,
                    quality=item.quality,
                )
            )
            continue
        for unit_index in range(quantity):
            expanded.append(
                DynamicOrderInput(
                    order_id=f"{item.order_id}-{unit_index + 1:02d}",
                    product_type=item.product_type,
                    quantity=1,
                    priority=item.priority,
                    due_time=item.due_time,
                    arrival_time=item.arrival_time,
                    quality=item.quality,
                )
            )
    return expanded


def summarize_order_sequence(
    records: Iterable[ScheduleRecord],
    order_attributes: Dict[str, Dict[str, float]] | None = None,
) -> List[OrderSequenceRow]:
    order_attributes = order_attributes or {}
    grouped: Dict[str, List[ScheduleRecord]] = {}
    for record in records:
        grouped.setdefault(record.order_id, []).append(record)

    pending_rows: List[OrderSequenceRow] = []
    for order_id, order_records in grouped.items():
        ordered = sorted(order_records, key=lambda item: (item.start_time, item.end_time))
        first = ordered[0]
        inspect_end = next(
            (record.end_time for record in ordered if record.process == "inspect"),
            0.0,
        )
        quality_result = _quality_from_branch(ordered)
        branch = "NG → R5缺陷品分拣" if quality_result == "NG" else "OK → R4锁付 → R5良品分拣"
        attrs = order_attributes.get(order_id, {})
        pending_rows.append(
            OrderSequenceRow(
                rank=0,
                order_id=order_id,
                product_type=first.product_type,
                priority=first.priority,
                arrival_time=float(attrs.get("arrival_time", 0.0)),
                due_time=float(attrs.get("due_time", 0.0)),
                quality_result=quality_result,
                first_start=first.start_time,
                inspect_end=inspect_end,
                completion_time=max(record.end_time for record in ordered),
                branch=branch,
                process_chain=" → ".join(record.process for record in ordered),
            )
        )

    pending_rows.sort(
        key=lambda row: (
            row.first_start,
            -row.priority,
            row.completion_time,
            row.order_id,
        )
    )
    return [
        OrderSequenceRow(
            rank=index,
            order_id=row.order_id,
            product_type=row.product_type,
            priority=row.priority,
            arrival_time=row.arrival_time,
            due_time=row.due_time,
            quality_result=row.quality_result,
            first_start=row.first_start,
            inspect_end=row.inspect_end,
            completion_time=row.completion_time,
            branch=row.branch,
            process_chain=row.process_chain,
        )
        for index, row in enumerate(pending_rows, start=1)
    ]


def _quality_from_branch(records: List[ScheduleRecord]) -> str:
    processes = {record.process for record in records}
    if "sort_defect" in processes:
        return "NG"
    return "OK"


def _expanded_order_attributes(order_inputs: Iterable[DynamicOrderInput]) -> Dict[str, Dict[str, float]]:
    attributes: Dict[str, Dict[str, float]] = {}
    for item in order_inputs:
        for unit_index in range(max(int(item.quantity), 1)):
            suffix = "" if int(item.quantity) == 1 else f"-{unit_index + 1:02d}"
            attributes[f"{item.order_id}{suffix}"] = {
                "arrival_time": float(item.arrival_time),
                "due_time": float(item.due_time),
            }
    return attributes
