"""Canonical object names for the rebuilt 8-robot CoppeliaSim scene.

The scene is generated by ``scripts/rename_scene_robots.py`` (robot
numbering), ``scripts/build_new_line_scene.py`` (base line content) and
``scripts/build_cabinet_product_scene.py`` (real STL cabinet product).
Robot roots live at ``/R1`` ... ``/R8``; cell fixtures, parts and targets
live below ``/FiveCR5A_Cell``.

Line layout:
    R1 shell loading and pallet location             gripper
    R2 horizontal rail installation                  magnetic pad
    R3 two vertical rail installations               slim gripper
    R4 PSU / servo / EDS installation                gripper
    R5 PLC / DMA / filter installation               vacuum
    R6 contactor / breaker / COM5 installation       gripper
    R7 four-point internal fastening                 screwdriver
    R8 door installation and latching                vacuum
"""

from __future__ import annotations


SCENE_ROOT = "/FiveCR5A_Cell"
SCENE_FILE = "compact_cell.ttt"
ROBOT_IDS = tuple(f"R{index}" for index in range(1, 9))
ARM_JOINT_ALIASES = tuple(f"joint{index}" for index in range(1, 7))

ROBOT_ROOTS = {robot_id: f"/{robot_id}" for robot_id in ROBOT_IDS}
# The detached /FiveCR5A_Cell/RobotBases/R*_Base discs were legacy visual
# supports and are intentionally removed by the final scene builder.  Resolve
# each robot's actual model-owned collision base instead.
ROBOT_BASES = {
    robot_id: f"/{robot_id}/base_link_respondable"
    for robot_id in ROBOT_IDS
}
ROBOT_TIPS = {
    "R1": "R1_gripper_tip",
    "R2": "R2_vacuum_tip",
    "R3": "R3_gripper_tip",
    "R4": "R4_gripper_tip",
    "R5": "R5_vacuum_tip",
    "R6": "R6_gripper_tip",
    "R7": "R7_tool_tip",
    "R8": "R8_vacuum_tip",
}
ROBOT_TOOL_ROOTS = {
    robot_id: f"/{robot_id}/{robot_id}T" for robot_id in ROBOT_IDS
}

TARGET_GROUPS = {robot_id: f"{robot_id}_Targets" for robot_id in ROBOT_IDS}
ROBOT_TARGET_NAMES = {
    "R1": (
        "R1_HOME_REF",
        "R1_SHELL_PICK_APP",
        "R1_SHELL_PICK_TCP",
        "R1_WB1_PLACE_APP",
        "R1_WB1_PLACE_TCP",
    ),
    "R2": (
        "R2_HOME_REF",
        "R2_RAIL_PICK_H_APP",
        "R2_RAIL_PICK_H_TCP",
        "R2_RAIL_PLACE_H_APP",
        "R2_RAIL_PLACE_H_TCP",
    ),
    "R3": (
        "R3_HOME_REF",
        "R3_RAIL_PICK_A_APP",
        "R3_RAIL_PICK_A_TCP",
        "R3_RAIL_PICK_B_APP",
        "R3_RAIL_PICK_B_TCP",
        "R3_RAIL_PLACE_A_APP",
        "R3_RAIL_PLACE_A_TCP",
        "R3_RAIL_PLACE_B_APP",
        "R3_RAIL_PLACE_B_TCP",
    ),
    "R4": (
        "R4_HOME_REF",
        "R4_PSU_PICK_APP", "R4_PSU_PICK_TCP",
        "R4_PSU_PLACE_APP", "R4_PSU_PLACE_TCP",
        "R4_SERVO_PICK_APP", "R4_SERVO_PICK_TCP",
        "R4_SERVO_PLACE_APP", "R4_SERVO_PLACE_TCP",
        "R4_EDS_PICK_APP", "R4_EDS_PICK_TCP",
        "R4_EDS_PLACE_APP", "R4_EDS_PLACE_TCP",
    ),
    "R5": (
        "R5_HOME_REF",
        "R5_PLC_PICK_APP",
        "R5_PLC_PICK_TCP",
        "R5_PLC_PLACE_APP",
        "R5_PLC_PLACE_TCP",
        "R5_DMA_PICK_APP", "R5_DMA_PICK_TCP",
        "R5_DMA_PLACE_APP", "R5_DMA_PLACE_TCP",
        "R5_FILTER_PICK_APP", "R5_FILTER_PICK_TCP",
        "R5_FILTER_PLACE_APP", "R5_FILTER_PLACE_TCP",
    ),
    "R6": (
        "R6_HOME_REF",
        "R6_BREAKER_PICK_APP",
        "R6_BREAKER_PICK_TCP",
        "R6_BREAKER_PLACE_APP",
        "R6_BREAKER_PLACE_TCP",
        "R6_CONTACTOR_PICK_APP",
        "R6_CONTACTOR_PICK_TCP",
        "R6_CONTACTOR_PLACE_APP",
        "R6_CONTACTOR_PLACE_TCP",
        "R6_COM5_PICK_APP", "R6_COM5_PICK_TCP",
        "R6_COM5_PLACE_APP", "R6_COM5_PLACE_TCP",
    ),
    "R7": (
        "R7_HOME_REF",
        "R7_SCREW_1_APP",
        "R7_SCREW_1_TCP",
        "R7_SCREW_2_APP",
        "R7_SCREW_2_TCP",
        "R7_SCREW_3_APP",
        "R7_SCREW_3_TCP",
        "R7_SCREW_4_APP",
        "R7_SCREW_4_TCP",
    ),
    "R8": (
        "R8_HOME_REF",
        "R8_DOOR_PICK_APP", "R8_DOOR_PICK_TCP",
        "R8_DOOR_PLACE_APP", "R8_DOOR_PLACE_TCP",
        "R8_LATCH_APP", "R8_LATCH_TCP",
    ),
}


def _build_target_paths() -> dict[str, str]:
    paths: dict[str, str] = {}
    for resource_id, target_names in ROBOT_TARGET_NAMES.items():
        group = TARGET_GROUPS[resource_id]
        for target_name in target_names:
            paths[target_name] = (
                f"{SCENE_ROOT}/Targets/{group}/{target_name}"
            )
    return paths


POINTS = _build_target_paths()
HOME_POINTS = {
    robot_id: POINTS[f"{robot_id}_HOME_REF"] for robot_id in ROBOT_IDS
}

PARTS = {
    "SHELL_STACK": f"{SCENE_ROOT}/Parts/Shell_Stack",
    "PRODUCT_REF": f"{SCENE_ROOT}/Parts/Cabinet_Product_REF",
}
BASKETS = {
    "R2_STAND": f"{SCENE_ROOT}/Baskets/R2_Stand",
    "R3_RAIL_RACK": f"{SCENE_ROOT}/Baskets/R3_Rail_Rack",
    "R4_DEVICE": f"{SCENE_ROOT}/Baskets/R4_Device_Basket",
    "R5_DEVICE": f"{SCENE_ROOT}/Baskets/R5_Device_Basket",
    "R6_DEVICE": f"{SCENE_ROOT}/Baskets/R6_Device_Basket",
    "R8_DOOR_SUPPLY": f"{SCENE_ROOT}/Baskets/R8_Door_Supply",
}
AREAS = {
    "WORKBENCH1": f"{SCENE_ROOT}/Areas/Workbench1_Area",
    "WORKBENCH2": f"{SCENE_ROOT}/Areas/Workbench2_Area",
    "HANDOFF": f"{SCENE_ROOT}/Areas/Handoff_Area",
    "STAGING": f"{SCENE_ROOT}/Areas/Staging_Area",
}
CONVEYORS = {
    "CABINET": f"{SCENE_ROOT}/Conveyors/Cabinet_Conveyor",
    "FINISHED": f"{SCENE_ROOT}/Conveyors/Finished_Conveyor",
}

# Scene-specific Cartesian safety envelopes for the validated simulation
# trajectories.  The legacy five-arm envelopes were removed together with
# the old motion stack; rebuild them here when the new R1-R8 motion layer
# is validated.
WORKSPACES = {}

ROS_TOPICS = {
    "GLOBAL_COMMAND": "/compact_cell/cmd",
    "MAIN_COMMAND": "/compact_cell/main_cmd",
    "TOOL_COMMAND": "/compact_cell/tool_cmd",
    "STATUS": "/compact_cell/status",
    "JOINT_COMMAND": "/compact_cell/joint_cmd",
    "JOINT_STATUS": "/compact_cell/joint_status",
    **{
        f"{robot_id}_COMMAND": f"/compact_cell/{robot_id.lower()}_cmd"
        for robot_id in ROBOT_IDS
    },
}

# Legacy command vocabulary.  The embedded scene scripts that consumed these
# strings were removed during the 8-robot rebuild; the sets are kept so the
# remaining scheduler process model (product_types.yaml / mock_scheduler.py)
# and its contract tests stay consistent until the new process model
# replaces them.
PROCESS_COMMANDS = {
    "RESET_CELL",
    "COLOR_NEXT",
    "COLOR_1",
    "COLOR_2",
    "COLOR_3",
    "SHOW_ASSEMBLY_SHELL",
    "SHOW_ASSEMBLY_PCB",
    "SHOW_ASSEMBLY_MODULE",
    "SHOW_ASSEMBLY_FULL",
    "SHOW_INSPECTION_FULL",
    "CAMERA_GOOD",
    "CAMERA_DEFECT",
    "CONVEYOR_GOOD",
    "CONVEYOR_DEFECT",
    "R1_BOX_PLACED",
    "R2_PCB_PLACED",
    "R3_MODULE_PLACED",
    "R1_TERMINAL_PLACED",
    "R3_PRODUCT_TO_INSPECTION",
    "R4_SCREW_DONE",
    "R5_SORT_GOOD_DONE",
    "R5_SORT_DEFECT_DONE",
}
QUALITY_COMMANDS = {"OK": "CAMERA_GOOD", "NG": "CAMERA_DEFECT"}
PROCESS_SIGNAL_UPDATES = {
    "RESET_CELL": ("cell_product_state", "reset"),
    "COLOR_NEXT": ("cell_product_state", "color_next"),
    "COLOR_1": ("cell_product_state", "color_1"),
    "COLOR_2": ("cell_product_state", "color_2"),
    "COLOR_3": ("cell_product_state", "color_3"),
    "SHOW_ASSEMBLY_SHELL": ("cell_product_state", "assembly_shell"),
    "SHOW_ASSEMBLY_PCB": ("cell_product_state", "assembly_pcb"),
    "SHOW_ASSEMBLY_MODULE": ("cell_product_state", "assembly_module"),
    "SHOW_ASSEMBLY_FULL": ("cell_product_state", "assembly_full"),
    "SHOW_INSPECTION_FULL": ("cell_product_state", "inspection_full"),
    "CAMERA_GOOD": ("cell_product_state", "camera_good"),
    "CAMERA_DEFECT": ("cell_product_state", "camera_defect"),
    "CONVEYOR_GOOD": ("cell_conveyor_state", "good"),
    "CONVEYOR_DEFECT": ("cell_conveyor_state", "defect"),
    "R1_BOX_PLACED": ("cell_product_state", "assembly_shell"),
    "R2_PCB_PLACED": ("cell_product_state", "assembly_pcb"),
    "R3_MODULE_PLACED": ("cell_product_state", "assembly_module"),
    "R1_TERMINAL_PLACED": ("cell_product_state", "assembly_full"),
    "R3_PRODUCT_TO_INSPECTION": ("cell_product_state", "inspection_full"),
    "R4_SCREW_DONE": ("cell_screw_state", "done"),
    "R5_SORT_GOOD_DONE": ("cell_conveyor_state", "good"),
    "R5_SORT_DEFECT_DONE": ("cell_conveyor_state", "defect"),
}

# Legacy tool-command vocabulary (Step02B controller removed).
TOOL_COMMANDS = {
    "R1_GRIPPER_OPEN",
    "R1_GRIPPER_CLOSE",
    "R1_GRIPPER_CLOSE_BOX",
    "R1_GRIPPER_CLOSE_TERMINAL",
    "R1_GRIPPER_CLOSE_MODULE",
    "R1_ATTACH_BOX",
    "R1_RELEASE_BOX_ASSEMBLY",
    "R1_ATTACH_MODULE",
    "R1_RELEASE_MODULE_ASSEMBLY",
    "R1_ATTACH_TERMINAL",
    "R1_RELEASE_TERMINAL_ASSEMBLY",
    "R2_VACUUM_ON",
    "R2_VACUUM_OFF",
    "R2_ATTACH_PCB",
    "R2_RELEASE_PCB_ASSEMBLY",
    "R3_GRIPPER_OPEN",
    "R3_GRIPPER_CLOSE",
    "R3_ATTACH_BOX",
    "R3_RELEASE_BOX_ASSEMBLY",
    "R3_ATTACH_ASSEMBLY_PRODUCT",
    "R3_RELEASE_PRODUCT_INSPECTION",
    "R4_SCREW_START",
    "R4_SCREW_STOP",
    "R5_GRIPPER_OPEN",
    "R5_GRIPPER_CLOSE",
    "R5_ATTACH_INSPECTION_PRODUCT",
    "R5_RELEASE_GOOD",
    "R5_RELEASE_DEFECT",
    "ALL_GRIPPERS_OPEN",
    "ALL_GRIPPERS_CLOSE",
}


def normalize_robot_id(robot_id: str) -> str:
    normalized = robot_id.strip().upper()
    if normalized not in ROBOT_ROOTS:
        raise KeyError(f"unknown robot id: {robot_id}")
    return normalized


def get_point_path(name: str) -> str:
    try:
        return POINTS[name]
    except KeyError as exc:
        raise KeyError(f"unknown target point: {name}") from exc


def get_robot_root_path(robot_id: str) -> str:
    return ROBOT_ROOTS[normalize_robot_id(robot_id)]


def get_robot_base_path(robot_id: str) -> str:
    return ROBOT_BASES[normalize_robot_id(robot_id)]


def get_home_path(robot_id: str) -> str:
    return HOME_POINTS[normalize_robot_id(robot_id)]


def get_tip_alias(robot_id: str) -> str:
    return ROBOT_TIPS[normalize_robot_id(robot_id)]


def get_joint_alias(robot_id: str, joint_num: int) -> str:
    normalize_robot_id(robot_id)
    if joint_num not in range(1, 7):
        raise ValueError(f"joint number must be 1..6, got {joint_num}")
    return ARM_JOINT_ALIASES[joint_num - 1]


def get_joint_path(robot_id: str, joint_num: int) -> str:
    """Return a path hint; clients should resolve the alias recursively."""
    normalized = normalize_robot_id(robot_id)
    return f"/{normalized}/{get_joint_alias(normalized, joint_num)}"


def resolve_object_path(name: str) -> str:
    if name.startswith("/"):
        return name
    for mapping in (
        POINTS,
        ROBOT_ROOTS,
        ROBOT_BASES,
        PARTS,
        BASKETS,
        AREAS,
        CONVEYORS,
    ):
        if name in mapping:
            return mapping[name]
    raise KeyError(f"unknown scene object name: {name}")
