"""Shared data types for the five-CR5A scheduling system."""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, List, Optional


class TaskStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    FINISHED = "finished"
    FAILED = "failed"
    WAITING = "waiting"


class RobotStatus(str, Enum):
    IDLE = "idle"
    BUSY = "busy"
    FAULT = "fault"


class QualityResult(str, Enum):
    OK = "OK"
    NG = "NG"


class ProcessType(str, Enum):
    BOX_FEED = "box_feed"
    PCB_INSTALL = "pcb_install"
    MODULE_INSTALL = "module_install"
    TERMINAL_INSTALL = "terminal_install"
    TRANSFER_TO_INSPECTION = "transfer_to_inspection"
    INSPECT = "inspect"
    SCREW = "screw"
    SORT_GOOD = "sort_good"
    SORT_DEFECT = "sort_defect"


@dataclass
class Order:
    """Order input for A/B/C electrical control box products."""

    order_id: str
    product_type: str
    priority: int
    quantity: int = 1
    due_time: float = 0.0
    arrival_time: float = 0.0

    def to_dict(self) -> dict:
        return {
            "order_id": self.order_id,
            "product_type": self.product_type,
            "priority": self.priority,
            "quantity": self.quantity,
            "due_time": self.due_time,
            "arrival_time": self.arrival_time,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "Order":
        return cls(
            order_id=d["order_id"],
            product_type=d["product_type"],
            priority=d.get("priority", 1),
            quantity=d.get("quantity", 1),
            due_time=d.get("due_time", 0.0),
            arrival_time=d.get("arrival_time", 0.0),
        )


@dataclass
class Task:
    """Task generated by the scheduler and consumed by robot/sim modules."""

    task_id: str
    order_id: str
    product_type: str
    process: str
    target_area: str
    target_point: str
    available_robots: List[str] = field(default_factory=list)
    duration: float = 5.0
    predecessors: List[str] = field(default_factory=list)
    priority: int = 1
    status: str = "pending"
    required_areas: List[str] = field(default_factory=list)
    scene_command: str = ""

    def to_dict(self) -> dict:
        return {
            "task_id": self.task_id,
            "order_id": self.order_id,
            "product_type": self.product_type,
            "process": self.process,
            "target_area": self.target_area,
            "target_point": self.target_point,
            "available_robots": self.available_robots,
            "duration": self.duration,
            "predecessors": self.predecessors,
            "priority": self.priority,
            "status": self.status,
            "required_areas": self.required_areas,
            "scene_command": self.scene_command,
        }


@dataclass
class TaskResult:
    """Task execution result returned by robot/sim modules."""

    task_id: str
    robot_id: str
    status: str
    start_time: float = 0.0
    end_time: float = 0.0
    message: str = ""
    quality_result: str = ""
    metrics: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "task_id": self.task_id,
            "robot_id": self.robot_id,
            "status": self.status,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "message": self.message,
            "quality_result": self.quality_result,
            "metrics": self.metrics,
        }


@dataclass
class RobotState:
    """Robot or schedulable resource state."""

    robot_id: str
    status: str = "idle"
    current_task: Optional[str] = None
    position: str = "home"
    utilization: float = 0.0
    completed_tasks: int = 0

    def to_dict(self) -> dict:
        return {
            "robot_id": self.robot_id,
            "status": self.status,
            "current_task": self.current_task,
            "position": self.position,
            "utilization": self.utilization,
            "completed_tasks": self.completed_tasks,
        }


@dataclass
class SystemSnapshot:
    """System snapshot for GUI refresh and logging."""

    timestamp: float = 0.0
    orders: List[Order] = field(default_factory=list)
    tasks: List[Task] = field(default_factory=list)
    robots: List[RobotState] = field(default_factory=list)
    logs: List[str] = field(default_factory=list)
    makespan: float = 0.0
    conflict_count: int = 0
